Repository eclipse/xtext-eclipse, pull requests merged in 2019-06, with the labels that each got.

#1089 [eclipse/xtext#1475] build against orbit 2019-09
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
  releng/org.eclipse.xtext.contributor/Xtext.setup
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target
Labels: releng

#1088 [eclipse/xtext#1473] bootstrap against 2.18
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#1091 [eclipse/xtext#1463] Configure timeout & timestamps
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#1000 Refactoring the test case accesses the workspace root.
  org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/builderState/EclipseResourceFileSystemAccessTest.java
  org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/jdt/MockJavaProjectProvider.java
  org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/ui/refactoring/participant/TextChangeCombinerTest.java
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/JavaProjectSetupUtil.java
  org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/autoedit/AutoEditTest.java
  org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/autoedit/Bug330096Test.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/encoding/EncodingTest.java
  org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/editor/autoedit/XtextAutoEditStrategyTest.java
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java
Labels: refactoring

#1094 Refactoring in xtext.ui.editor.quickfix.IssueResolutionAcceptor class.
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/IssueResolutionAcceptor.java
Labels: refactoring

#1099 [eclipse/xtext#1485] update to mwe 2.11
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
Labels: releng

#1098 increased timeout cause ci.eclipse.org gets more and more crappy
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#1100 Attempt to fix Storage2URIMapper for Java9 and beyond
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.xtend
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
Labels: bug

#1101 fixed broken setup
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: releng

#1107 [eclipse/xtext-xtend#818] Add classgraph to target platform
  releng/org.eclipse.xtext.contributor/Xtext.setup
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201906.target
Labels: enhancement

#1110 [eclipse/xtext-xtend#818] Add classgraph to domainmodel tp
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
Labels: bug

#1111 [eclipse/xtext1475] use 2019-09 in latest target platform
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
Labels: releng

#1114 [eclipse/xtext-core#1178] Use one 1 cpu in every pod
  CBI.Jenkinsfile
Labels: releng

#1112 [eclipse/xtext#1475] prepared oomph for 2019-09
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: releng

#1104 [#1103] Extend the Statemachine Xtext Editor folding capabilities.
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/src/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineFoldingTest.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/tests/StatemachineFoldingTest.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/StatemachineUiModule.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/folding/StatemachineFoldingRegionProvider.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/StatemachineUiModule.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/folding/StatemachineFoldingRegionProvider.java
Labels: enhancement

#1115 [eclipse/xtext#1459] Change p2.buildship value to use Buildship 3.x
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: releng

#1117 [eclipse/xtext#1495] Use unique label for each agent
  CBI.Jenkinsfile
Labels: releng

#1120 [eclipse/xtext#1431] Tweak resource constraints
  CBI.Jenkinsfile
Labels: releng

#1116 [#376] migrated workflow to new generator
  org.eclipse.xtext.xtext.ui.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.tests/plugin.xml_gen
  org.eclipse.xtext.xtext.ui.tests/src-gen/META-INF/services/org.eclipse.xtext.ISetup
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/AbstractEcore2XtextTestRuntimeModule.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/Ecore2XtextTestStandaloneSetupGenerated.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/AbstractEcore2XtextTestIdeModule.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/contentassist/antlr/Ecore2XtextTestParser.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/contentassist/antlr/PartialEcore2XtextTestContentAssistParser.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/contentassist/antlr/internal/InternalEcore2XtextTest.g
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/contentassist/antlr/internal/InternalEcore2XtextTest.tokens
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/contentassist/antlr/internal/InternalEcore2XtextTestLexer.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/contentassist/antlr/internal/InternalEcore2XtextTestParser.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/parser/antlr/Ecore2XtextTestAntlrTokenFileProvider.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/parser/antlr/Ecore2XtextTestParser.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/parser/antlr/internal/InternalEcore2XtextTest.g
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/parser/antlr/internal/InternalEcore2XtextTestLexer.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/parser/antlr/internal/InternalEcore2XtextTestParser.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/scoping/Ecore2XtextTestScopeProvider.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/services/Ecore2XtextTestGrammarAccess.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ui/AbstractEcore2XtextTestUiModule.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ui/Ecore2XtextTestExecutableExtensionFactory.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ui/contentassist/AbstractEcore2XtextTestProposalProvider.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ui/contentassist/antlr/Ecore2XtextTestParser.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ui/quickfix/Ecore2XtextTestQuickfixProvider.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/validation/Ecore2XtextTestValidator.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/tests/internal/TestsActivator.java
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/GenerateTestLanguages.mwe2
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/Ecore2XtextTestIdeModule.java
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/ecore2xtext/ide/Ecore2XtextTestIdeSetup.java
Labels: releng
