Repository eclipse/xtext-eclipse, pull requests merged in 2019-05, with the labels that each got.

#1061 Ade asm710
  org.eclipse.xtext.common.types.eclipse.tests/META-INF/MANIFEST.MF_gen
  org.eclipse.xtext.purexbase.eclipse.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/META-INF/MANIFEST.MF
  releng/org.eclipse.xtext.contributor/Xtext.setup
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target
Labels: releng

#1067 [eclipse/xtext#1437] Bootstrap against 2.18.0.M2
  org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.java
  org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/junit/formatter/FormatterTester.java
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#1062 Prevent glitchy outline select
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/OutlinePage.java
Labels: bug, confirmed

#1059 [eclipse/xtext#1384] Convert to Declarative Pipeline
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#1075 [eclipse/xtext-core#1149] Apply proper restore logic also to SmokeTest infra
  org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/smoketest/internal/WrappingInjectorProvider.java
Labels: bug

#1058 [#1050] Add context menu actions to ReferenceSearchViewPage
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/Messages.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResultContentProvider.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchViewPage.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchViewPageActions.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/messages.properties
Labels: new_feature

#1079 [eclipse/xtext#1458] fixed casing for target platform variable
  CBI.Jenkinsfile
  Jenkinsfile
Labels: releng

#1081 fixed more https issues
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: releng

#1076 [#1066] Pass all participating projects along with BuildData
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/IBuilderState.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildData.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ProjectOpenedOrClosedListener.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/SetWithProjectNames.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
Labels: enhancement

#1077 [eclipse/xtext#1460] Two phase lock of the workspace in BuilderState.load
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/AbstractBuilderState.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
Labels: bug

#1083 [#1460] Handle shutdown scenario properly
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/AbstractBuilderState.java
  org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/SharedModule.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.xtend
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/scoping/namespaces/AbstractJavaProjectsStateTest.java
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java
  org.eclipse.xtext.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/workspace/WorkspaceLockAccess.java
Labels: bug
