Repository eclipse/xtext-eclipse, pull requests merged in 2019-02, with the labels that each got.

#959 set minimal mwe version to the one from oxygen
  org.eclipse.xtext.builder.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types.eclipse.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.eclipse.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ui.codetemplates/META-INF/MANIFEST.MF
  org.eclipse.xtext.ui.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui/META-INF/MANIFEST.MF
Labels: releng

#960 Refactoring the Xtext UI Test Infrastructure.
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractEditorDoubleClickTextSelectionTest.xtend
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractEditorTest.java
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.xtend
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHoverTest.xtend
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.xtend
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.xtend
  org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractEditorDoubleClickTextSelectionTest.java
  org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHighlightingTest.java
  org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHoverTest.java
  org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.java
  org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/occurrences/MarkOccurrencesTest.java
  org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.xtend
  org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.java
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/OutlineTest.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/ui/tests/OutlineTest.java
Labels: refactoring

#961 Speed up the Xtext UI Test cases.
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/JavaClassPathResourceForIEditorInputFactoryTest.java
  org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.xtend
  org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.java
Labels: refactoring

#962 [eclipse/xtext#1391] pin guava version to 21
  org.eclipse.xtext.builder/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.testlanguages.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.junit/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.ui.testing/META-INF/MANIFEST.MF
Labels: releng

#963 [#909] Optimize useage of org.eclipse.xtext.common.types.shared depend.
  org.eclipse.xtext.xbase.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui/META-INF/MANIFEST.MF
Labels: refactoring

#966 [#965] Fixed BasicIndexOutOfBoundsException in Domainmodel Codemining
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/codemining/DomainmodelCodeMiningProvider.java
Labels: bug

#970 Refactoring the DomainmodelHyperlinkHelper in the Domain-Model Example.
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/navigation/DomainmodelHyperlinkHelper.java
Labels: refactoring

#972 [eclipse/xtext#1394] bootstrap against 2.17.0.M2
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#978 Added Possibility for Textual Multi Quickfixes
  org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/quickfix/ui/quickfix/QuickfixCrossrefTestLanguageQuickfixProvider.java
  org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/quickfix/validation/QuickfixCrossrefTestLanguageValidator.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractQuickfixTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/ITextualMultiModification.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/MarkerResolutionGenerator.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/TextualMultiModificationWorkbenchMarkerResolutionAdapter.java
Labels: new_feature

#982 fixed guava deprecations
  org.eclipse.xtext.m2e/src/org/eclipse/xtext/m2e/XtextProjectConfigurator.java
Labels: refactoring

#975 [eclipse/xtext#1283] update to MWE 2.10
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
Labels: releng

#990 Avoid NPE during cleanup build job
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ProjectOpenedOrClosedListener.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/XtextResourceSetProvider.java
Labels: bug

#989 Bug 410479 - [grammar] Add quickfix splitting keywords with spaces.
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.xtend
  org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.java
  org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProvider.java
Labels: new_feature

#993 [#410479] Refactoring the XtextGrammarQuickfixTest test cases.
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.xtend
  org.eclipse.xtext.xtext.ui.tests/xtend-gen/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixTest.java
Labels: refactoring
