Repository eclipse/xtext-eclipse, pull requests merged in 2019-11, with the labels that each got.

#1239 [no-ticket] Fixed warnings
  org.eclipse.xtext.junit4.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.purexbase.eclipse.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ui.codetemplates/META-INF/MANIFEST.MF
  org.eclipse.xtext.ui.testing/build.properties
  org.eclipse.xtext.ui.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.testlanguages.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ide/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/xbase.tutorial/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.tests/META-INF/MANIFEST.MF
Labels: releng

#1240 update docs from website-master
  org.eclipse.xtext.doc/contents/103_domainmodelnextsteps.html
  org.eclipse.xtext.doc/contents/303_runtime_concepts.html
  org.eclipse.xtext.doc/contents/310_eclipse_support.html
Labels: refactoring

#1246 [releng] Bootstrap against 2.20.0.M2
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1260 [#1259] Statemachine example: add New Project Wizard/New File Wizard.
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/AbstractTemplate.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/NewProjectWizardTemplateSelectionPage.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/.classpath
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/build.properties
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/icons/mrsgrantssecretcompartment.png
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/icons/new_Statemachine_proj.gif
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/icons/project_template.png
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/plugin.xml
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src-gen/org/eclipse/xtext/example/fowlerdsl/ui/AbstractStatemachineUiModule.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/Messages.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/StatemachineFileTemplateProvider.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/StatemachineProjectTemplateProvider.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/TemplateContent.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/messages.properties
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/EmptyFile.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/MrsGrantsSecretCompartmentsFile.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/MrsGrantsSecretCompartmentsProject.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/StatemachineFileTemplateProvider.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/StatemachineProjectTemplateProvider.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/TemplateContent.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/GenerateStatemachine.mwe2
Labels: enhancement

#1262 moved mwe deps to build.properties + removed old CodetemplatesGeneratorFragment
  org.eclipse.xtext.ui.codetemplates/.classpath
  org.eclipse.xtext.ui.codetemplates/META-INF/MANIFEST.MF
  org.eclipse.xtext.ui.codetemplates/build.properties
  org.eclipse.xtext.ui.codetemplates/deprecated/org/eclipse/xtext/ui/codetemplates/generator/CodetemplatesGeneratorFragment.java
Labels: releng

#1264 [#1259] Add New File Wizard to the Statemachine example.
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/.classpath
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/icons/file_template.png
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/icons/new_Statemachine_file.png
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/plugin.xml
Labels: enhancement

#1266 avoid 'Directory is empty. Can't process' warning
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#1255 [#251] Remove workaround for bug#474003
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
Labels: refactoring

#1247 [eclipse/xtext#1573] Provide proper build.properties
  org.eclipse.xtext.builder.tests/.classpath
  org.eclipse.xtext.builder.tests/build.properties
  org.eclipse.xtext.builder/.classpath
  org.eclipse.xtext.builder/build.properties
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/EMFBasedPersister.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuildManagerAccess.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ToBeBuiltComputer.java
  org.eclipse.xtext.common.types.shared.jdt38/build.properties
  org.eclipse.xtext.common.types.ui/build.properties
  org.eclipse.xtext.junit4.tests/build.properties
  org.eclipse.xtext.purexbase.eclipse.tests/build.properties
  org.eclipse.xtext.purexbase.ui/build.properties
  org.eclipse.xtext.testlanguages.ui/build.properties
  org.eclipse.xtext.ui.codetemplates.tests/build.properties
  org.eclipse.xtext.ui.codetemplates.ui/build.properties
  org.eclipse.xtext.ui.codetemplates/build.properties
  org.eclipse.xtext.ui.shared/build.properties
  org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/ListenerRegistrar.java
  org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/SharedModule.java
  org.eclipse.xtext.ui.testing/.classpath
  org.eclipse.xtext.ui.testing/build.properties
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJdtImplTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/JavaClassPathResourceForIEditorInputFactoryTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/util/JarPackageFragmentRootTestUtil.java
  org.eclipse.xtext.ui/build.properties
  org.eclipse.xtext.xbase.junit/.classpath
  org.eclipse.xtext.xbase.junit/build.properties
  org.eclipse.xtext.xbase.testlanguages.ui/build.properties
  org.eclipse.xtext.xbase.ui.testing/.classpath
  org.eclipse.xtext.xbase.ui.testing/build.properties
  org.eclipse.xtext.xbase.ui/build.properties
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/StatemachineProjectTemplateProvider.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/wizard/messages.properties
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/wizard/MrsGrantsSecretCompartmentsProject.java
  org.eclipse.xtext.xtext.ui.tests/build.properties
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/templates/XtextTemplateContextTypeRegistryTest.java
  org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/Activator.java
  org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/XtextHyperlinkHelper.java
Labels: releng

#1273 [#1229] Xtext Statemachine Example: add wizard generateToolbarButton.
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/plugin.xml
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/GenerateStatemachine.mwe2
Labels: enhancement

#1276 [releng] Bootstrap against 2.20.0.M3
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1278 use newest lsp4j. no longer part of composite cause nobody knows how that is maintained
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: releng
