Repository eclipse/xtext-eclipse, pull requests merged in 2019-04, with the labels that each got.

#1028 use https to access typefox jenkins
  README.md
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#1019 [eclipse/xtext#1412] oomph against 4.11 release and 4.12 I-Builds
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: releng

#1033 [eclipse/xtext#1424] Change default Jenkins
  README.md
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-oxygen.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-photon.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201809.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201812.target
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-r201903.target
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#1034 [eclipse/xtext#1403] Improve progress feedback
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/BatchModification.java
Labels: enhancement

#1035 [eclipse/xtext#1173] set discouraged access to warning
  org.eclipse.xtext.builder.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.builder/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.builder/META-INF/MANIFEST.MF
  org.eclipse.xtext.common.types.eclipse.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.common.types.ui/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.eclipse.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.junit4/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.purexbase.eclipse.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.testlanguages.ui/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui.codetemplates.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui.codetemplates.ui/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui.codetemplates/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui.shared/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui.testing/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xbase.junit/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase.testlanguages.ui/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase.ui.testing/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase.ui.tests/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.xbase.ui/META-INF/MANIFEST.MF
Labels: releng

#1037 [eclipse/xtext#1309] Extend initial Jenkinsfile for CJE
  1-maven-build.sh
  CBI.Jenkinsfile
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/ContentAssistProcessorTestBuilder.java
  org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/RefactoringDocumentProviderTest.java
  pom.xml
  releng/org.eclipse.xtext.p2-repository/pom.xml
Labels: releng

#1041 [eclipse/xtext#1403] Improve progress reporting
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/edit/BatchModification.java
Labels: enhancement

#1042 [xtext-extras#408] Fixed regression in injector provider
  org.eclipse.xtext.ui.codetemplates.tests/src-gen/org/eclipse/xtext/ui/codetemplates/tests/CodetemplatesInjectorProvider.java
  org.eclipse.xtext.ui.codetemplates.tests/src-gen/org/eclipse/xtext/ui/codetemplates/tests/SingleCodetemplateInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/bracketmatching/tests/BmTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/BacktrackingContentAssistTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug286935TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug287941TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug288734TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug288760TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug289187TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug291022TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug303200TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug304681TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug307519TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug309949TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug332217TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug347012TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug348199TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug348427TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug360834TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug377311TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/Bug381381TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/ContentAssistContextTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/ContentAssistCustomizingTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/ContentAssistNoTerminalExtensionTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/CrossReferenceProposalTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/DatatypeRuleTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/DomainModelTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/GH341TestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/LookAheadContentAssistTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/ParameterizedExpressionsTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/ParametersTestLanguageExInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/ParametersTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/TwoContextsTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/TwoParametersTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/tests/UnorderedGroupsTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/encoding/tests/EncodingUiTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/outline/tests/OutlineTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/enumrules/tests/EnumRulesUiTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/linking/tests/ImportUriUiTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/parser/keywords/tests/KeywordsUiTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/quickfix/tests/QuickfixCrossrefTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/refactoring/tests/RefactoringTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/refactoring/tests/ReferringTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/testlanguages/tests/ContentAssistTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/testlanguages/tests/ReferenceGrammarUiTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/tests/FoldingTestLanguageInjectorProvider.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/tests/TestLanguageInjectorProvider.java
  org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/XbaseInjectorProvider.java
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.tests/src-gen/org/eclipse/xtext/example/arithmetics/tests/ArithmeticsInjectorProvider.java
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src-gen/org/eclipse/xtext/example/domainmodel/tests/DomainmodelInjectorProvider.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.tests/src-gen/org/eclipse/xtext/example/fowlerdsl/tests/StatemachineInjectorProvider.java
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.tests/src-gen/org/eclipse/xtext/example/homeautomation/tests/RuleEngineInjectorProvider.java
Labels: bug

#1043 [eclipse/xtext#1422] update to tycho 1.4.0
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#1046 [eclipse/xtext#1430] added missing tp to CBI
  CBI.Jenkinsfile
Labels: releng

#1049 refactoring2: improved handling of 'IChangeSerializer' instance in 'ResourceRelocationProcessor'
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.xtend
  org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/participant/ResourceRelocationProcessor.java
Labels: enhancement

#987 [eclipse/xtext-eclipse#986] BuilderDeltaConverter JDT leak
  org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/notification/DeltaConverter.java
Labels: bug, performance

#1016 [bug545343] Avoid validation of projects without Xtext nature
  org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/SimpleProjectsIntegrationTest.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ClosedProjectsQueue.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
Labels: bug

#1054 [eclipse/xtext#1434] Upgrade to xtext-buildenv 0.7
  CBI.Jenkinsfile
Labels: releng

#1052 Also consider the listener job to be a manual build job
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/ProjectOpenedOrClosedListener.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperTest.java
Labels: bug

#1057 [eclipse/xtext-xtend#397] Support for ternary expressions and try with resource
  org.eclipse.xtext.purexbase.ui/src-gen/org/eclipse/xtext/purexbase/ui/contentassist/AbstractPureXbaseProposalProvider.java
  org.eclipse.xtext.xbase.ui.tests/suites/org/eclipse/xtext/xbase/ui/tests/editor/ContentAssistSuite.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/XbaseProposalProvider.java
Labels: new_feature
