Repository eclipse/xtext-eclipse, pull requests merged in 2019-08, with the labels that each got.

#1157 [eclipse/xtext#1526] Remove old CBI.Jenkinsfile
  CBI.Jenkinsfile
Labels: releng

#1159 [eclipse/xtext-lib#224] Stable method order when using Delegate
  org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/hierarchy/DeferredHierarchyBuilder.java
Labels: bug

#1158 [#1155] Avoid assumptions about the used implementation of IXtextDocument
  org.eclipse.xtext.purexbase.ui/src/org/eclipse/xtext/purexbase/ui/autoedit/ReplAutoEdit.java
  org.eclipse.xtext.ui.codemining/src/org/eclipse/xtext/ui/codemining/AbstractXtextCodeMiningProvider.java
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.xtend
  org.eclipse.xtext.ui.testing/xtend-gen/org/eclipse/xtext/ui/testing/AbstractHyperlinkingTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/ImportURINavigationTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/SimpleEditorTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/Bug369087Test.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/compare/DefaultMergeViewer.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/compare/DefaultViewerCreator.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/PresentationDamager.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextInformationProvider.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextSourceViewer.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextSourceViewerConfiguration.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/ContentAssistContext.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/RepeatedContentAssistProcessor.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/XtextContentAssistProcessor.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/doubleClicking/LexerTokenAndCharacterPairAwareStrategy.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditor.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorFactory.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorModelAccess.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/formatting/ContentFormatterFactory.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/formatting2/ContentFormatter.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/AbstractEObjectHover.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/DefaultHyperlinkDetector.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/DocumentTokenSourceAccess.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/IXtextDocument.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/PartitionTokenScanner.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentUtil.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/OutlinePage.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/AbstractIssueResolutionProviderAdapter.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/MarkerResolutionGenerator.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/quickfix/XtextQuickAssistProcessor.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/XtextDocumentReconcileStrategy.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/XtextReconciler.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/HighlightingReconciler.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/TokenScanner.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/SyncUtil.java
  org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.xtend
  org.eclipse.xtext.xbase.ui.tests/xtend-gen/org/eclipse/xtext/xbase/ui/tests/bug462047/Bug462047Test.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/XbaseDocumentProvider.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseDispatchingEObjectTextHover.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/templates/XbaseTemplateContext.java
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src/org/eclipse/xtext/example/arithmetics/ui/autoedit/InterpreterAutoEdit.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/autoedit/InterpreterAutoEdit.java
Labels: enhancement

#1162 [#1161] ExternalAntlrGeneratorFragment produces consistent output
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/bracketmatching/services/BmTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/BacktrackingContentAssistTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug287941TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug291022TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug303200TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug304681TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug309949TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug332217TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug348199TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug348427TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug360834TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug381381TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ContentAssistCustomizingTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/LookAheadContentAssistTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ParameterizedExpressionsTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ParametersTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/TwoParametersTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/xmleditor/CustomInternalXmlContentAssistLexer.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/xmleditor/CustomInternalXmlHighlightingLexer.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/xmleditor/CustomInternalXmlRuntimeLexer.java
  org.eclipse.xtext.ui.tests/src/org/eclipse/xtext/ui/tests/GenerateTestLanguages.mwe2
Labels: bug

#1163 InterpreterAutoEdit is not instantiated by Guice
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src/org/eclipse/xtext/example/arithmetics/ui/autoedit/AutoEditStrategy.xtend
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/autoedit/AutoEditStrategy.java
Labels: bug

#1166 preserve parameter names during compilation with tycho
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#1168 fixed broken junit 5 version in oomph setup
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: releng

#1170 bootstrap against m3
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng
