Repository eclipse/xtext-eclipse, pull requests merged in 2020-01, with the labels that each got.

#1302 go back to orbit 2020-03
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: releng

#1312 [eclipse/xtext#1642] regenerated xtend code with latest xtend
  org.eclipse.xtext.builder/xtend-gen/org/eclipse/xtext/builder/debug/IBuildLogger.java
  org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/refactoring2/rename/ISimpleNameProvider.java
Labels: releng

#1315 [releng] Bootstrap against 2.21.0.M1
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1316 improved clustering in IteratorJob (Open Model Element Dialog)
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/search/IteratorJob.java
Labels: performance

#1322 [eclipse/xtext#1643] update to tycho 1.6.0
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: releng

#1321 Some cosmetic changes to Domainmodel validator
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.java
Labels: refactoring

#1323 [eclipse/xtext#1595] Escape branch name for k8s label
  Jenkinsfile
Labels: releng

#1324 [eclipse/xtext#1629] moved xbase workflow to not to prefer xtend
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/annotations/ui/XbaseWithAnnotationsUiModule.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/annotations/ui/XbaseWithAnnotationsUiModule.xtend
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/XbaseUiModule.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/XbaseUiModule.xtend
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/XtypeUiModule.java
  org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/XtypeUiModule.xtend
  org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/annotations/ui/XbaseWithAnnotationsUiModule.java
  org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/XbaseUiModule.java
  org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/XtypeUiModule.java
Labels: refactoring

#1327 removed duplicate extra requirement
  releng/org.eclipse.xtext.tycho.tests.parent/pom.xml
Labels: releng

#1325 [eclipse/xtext#1629] ported more Xtend code to Java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/MonitorBasedCancelIndicator.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/MonitorBasedCancelIndicator.xtend
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/debug/IBuildLogger.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/debug/IBuildLogger.xtend
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/BuilderDeltaConverter.java
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/BuilderDeltaConverter.xtend
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/UnconfirmedStructuralChangesDelta.java
  org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/xtext/ui/ProjectAwareResourceDescriptionsProvider.java
  org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/xtext/ui/ProjectAwareResourceDescriptionsProvider.xtend
Labels: refactoring
