Repository eclipse/xtext-eclipse, pull requests merged in 2020-11, with the labels that each got.

#1578 [#1577] switched order of while condition to make sure that we dont skip any things that are put to request queue
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/ParallelBuilderParticipant.java
Labels: bug

#1579 [releng] Bootstrap against 2.24.0.M2
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1585 regenerated docs
  org.eclipse.xtext.doc/contents/302_configuration.html
  org.eclipse.xtext.doc/contents/350_continuous_integration.html
Labels: releng

#1588 [#1587] Add license feature
  releng/org.eclipse.xtext.contributor/Xtext.setup
Labels: enhancement

#1591 [releng] Update MWE to 1.6.0/2.12.0
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
Labels: bot, releng

#1586 regenerated languages
  org.eclipse.xtext.builder.tests/src-gen/org/eclipse/xtext/builder/tests/services/BuilderTestLanguageGrammarAccess.java
  org.eclipse.xtext.common.types.eclipse.tests/src-gen/org/eclipse/xtext/common/types/xtext/ui/services/ContentAssistTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.codetemplates/src-gen/org/eclipse/xtext/ui/codetemplates/services/CodetemplatesGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/bracketmatching/services/BmTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/BacktrackingContentAssistTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug286935TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug287941TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug288734TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug288760TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug289187TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug291022TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug303200TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug304681TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug309949TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug332217TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug348199TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug348427TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug360834TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/Bug381381TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ContentAssistContextTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ContentAssistNoTerminalExtensionTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/DatatypeRuleTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/DomainModelTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/GH341TestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/LookAheadContentAssistTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ParameterizedExpressionsTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ParametersTestLanguageExGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/ParametersTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/TwoParametersTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/services/UnorderedGroupsTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/linking/services/ImportUriUiTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/parser/keywords/services/KeywordsUiTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/quickfix/services/QuickfixCrossrefTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/services/FoldingTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/testlanguages/services/ContentAssistTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/testlanguages/services/ReferenceGrammarUiTestLanguageGrammarAccess.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/xmleditor/services/XmlGrammarAccess.java
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/src-gen/org/eclipse/xtext/example/arithmetics/services/ArithmeticsGrammarAccess.java
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src-gen/org/eclipse/xtext/example/domainmodel/services/DomainmodelGrammarAccess.java
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/src-gen/org/eclipse/xtext/example/fowlerdsl/services/StatemachineGrammarAccess.java
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/src-gen/org/eclipse/xtext/example/homeautomation/services/RuleEngineGrammarAccess.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/services/Ecore2XtextTestGrammarAccess.java
  org.eclipse.xtext.xtext.ui.tests/src-gen/org/eclipse/xtext/xtext/ui/ecore2xtext/ui/Ecore2XtextTestExecutableExtensionFactory.java
Labels: releng

#1595 [releng] Bootstrap against 2.24.0.M3
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1596 added missing settings files
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ide/.settings/org.eclipse.core.resources.prefs
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ide/.settings/org.eclipse.jdt.core.prefs
Labels: bug
