Repository eclipse/xtext-eclipse, pull requests merged in 2020-04, with the labels that each got.

#1388 clean manifests regarding generator dependency
  org.eclipse.xtext.builder.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.builder.tests/build.properties
  org.eclipse.xtext.eclipse.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.eclipse.tests/build.properties
Labels: releng

#1401 [releng] Bootstrap against 2.22.0.M1
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1416 Refactoring the XtextGrammarQuickfixProviderTest test cases.
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java
Labels: refactoring
