Repository eclipse/xtext-eclipse, pull requests merged in 2020-05, with the labels that each got.

#1423 [eclipse/xtext-core#1462] Regenerated languages
  org.eclipse.xtext.common.types.eclipse.tests/plugin.xml_gen
  org.eclipse.xtext.testlanguages.ui/plugin.xml_gen
  org.eclipse.xtext.ui.codetemplates/src-gen/org/eclipse/xtext/ui/codetemplates/parser/antlr/internal/InternalCodetemplatesParser.g
  org.eclipse.xtext.ui.codetemplates/src-gen/org/eclipse/xtext/ui/codetemplates/parser/antlr/internal/InternalCodetemplatesParser.java
  org.eclipse.xtext.ui.codetemplates/src-gen/org/eclipse/xtext/ui/codetemplates/parser/antlr/internal/InternalSingleCodetemplateParser.g
  org.eclipse.xtext.ui.codetemplates/src-gen/org/eclipse/xtext/ui/codetemplates/parser/antlr/internal/InternalSingleCodetemplateParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBacktrackingContentAssistTestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBacktrackingContentAssistTestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug286935TestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug286935TestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug287941TestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug287941TestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug289187TestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug289187TestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug304681TestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug304681TestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug332217TestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug332217TestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug348427TestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug348427TestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug360834TestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalBug360834TestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalParameterizedExpressionsTestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalParameterizedExpressionsTestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalUnorderedGroupsTestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/editor/contentassist/parser/antlr/internal/InternalUnorderedGroupsTestLanguageParser.java
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/parser/keywords/parser/antlr/internal/InternalKeywordsUiTestLanguage.g
  org.eclipse.xtext.ui.tests/src-gen/org/eclipse/xtext/ui/tests/parser/keywords/parser/antlr/internal/InternalKeywordsUiTestLanguageParser.java
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics.ui/src-gen/org/eclipse/xtext/example/arithmetics/ui/AbstractArithmeticsUiModule.java
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src-gen/org/eclipse/xtext/example/domainmodel/parser/antlr/internal/InternalDomainmodel.g
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/src-gen/org/eclipse/xtext/example/domainmodel/parser/antlr/internal/InternalDomainmodelParser.java
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/src-gen/org/eclipse/xtext/example/homeautomation/parser/antlr/internal/InternalRuleEngineParser.g
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/src-gen/org/eclipse/xtext/example/homeautomation/parser/antlr/internal/InternalRuleEngineParser.java
Labels: bug

#1419 Refactoring the org.eclipse.xtext.xtext.ui test cases.
  org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/editor/autoedit/XtextAutoEditStrategyTest.java
  org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/refactoring/XtextGrammarRefactoringIntegrationTest.java
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/SemanticHighlightingTest.java
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/hyperlinking/HyperlinkHelperTest.java
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/outline/XtextOutlineTreeProviderTest.java
  org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java
Labels: refactoring

#1431 [releng] Bootstrap against 2.22.0.M2
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1437 Remove unused interface
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/notification/IStateChangeEventBroker.java
Labels: technical_debt

#1438 [eclipse/xtext#1738] removed no longer needed icu dependency
  org.eclipse.xtext.eclipse.tests/META-INF/MANIFEST.MF
  org.eclipse.xtext.ui.codetemplates/META-INF/MANIFEST.MF
  org.eclipse.xtext.ui/META-INF/MANIFEST.MF
  org.eclipse.xtext.xtext.ui.examples/projects/arithmetics/org.eclipse.xtext.example.arithmetics/build.properties
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/build.properties
  org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl/build.properties
  org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation/build.properties
Labels: releng

#1436 [#1435] Remove listener from index when content provider is disposed
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/ReferenceSearchResultContentProvider.java
Labels: bug

#1439 marked xpand/xtend(1) depending XtendXtext2EcorePostProcessor as deprecated
  org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ecoreInference/ProjectAwareXtendXtext2EcorePostProcessor.java
  org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/XtextUiModule.java
Labels: technical_debt

#1442 org.eclipse.xtext.ui.tests.editor.quickfix refactoring.
  org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/quickfix/SpellingQuickfixTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractQuickfixTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/IssueDataTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/LinkingErrorTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.xtend
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.java
Labels: refactoring

#1445 [eclipse/xtext#1765] update to MWE 2.11.3.M3
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
Labels: releng

#1446 Refactoring the org.eclipse.xtext.ui.tests.editor.quickfix test cases.
  org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.java
  org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/quickfix/SpellingQuickfixTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractQuickfixTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/IssueDataTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/LinkingErrorTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.xtend
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.java
Labels: refactoring

#1444 [eclipse/xtext-core#1466] Send proper events for dirty state changes
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateEditorSupport.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateManager.java
Labels: new_feature

#1452 [#1450] adapted JavaBuilderState to change in field type of State.references
  org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/notification/JavaBuilderState.java
Labels: technical_debt

#1449 [#1447] Rename AbstractQuickfixTest to AbstractMultiQuickfixTest.
  org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/quickfix/SpellingQuickfixTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/AbstractMultiQuickfixTest.java
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.xtend
  org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.xtend
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/CompositeQuickfixTest.java
  org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/quickfix/MultiQuickFixTest.java
Labels: refactoring

#1453 Refactoring the RenameRefactoringIntegrationTest test cases.
  org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/RenameRefactoringIntegrationTest.java
Labels: refactoring

#1457 [eclipse/xtext-core#1499] Stricter JavaDoc validation on org.eclipse.xtext.ui
  org.eclipse.xtext.ui/.settings/org.eclipse.jdt.core.prefs
  org.eclipse.xtext.ui/deprecated/org/eclipse/xtext/ui/editor/syntaxcoloring/IHighlightedPositionAcceptor.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/XtextUIMessages.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/TextViewerJoinLinesAction.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/IXtextDocumentContentObserver.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/ResourceForIEditorInputFactory.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/AbstractPreferencePage.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/preferences/fields/AbstractMasterDetailsFieldEditor.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/ReplaceRegion.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/HighlightingPresenter.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DefaultReferenceUpdater.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/IStorage2UriMapperJdtExtensions.java
  org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/ResourceUtil.java
Labels: releng

#1458 [eclipse/xtext#1770] update to mwe 2.11.3 final
  org.eclipse.xtext.doc/contents/350_continuous_integration.html
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
  releng/org.eclipse.xtext.target/org.eclipse.xtext.target-latest.target
Labels: releng

#1461 [releng] Bootstrap against 2.22.0.M3
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1462 [eclipse/xtext#1769] Removed jnlp image name from pod template
  Jenkinsfile
Labels: releng
