Repository eclipse/xtext-eclipse, pull requests merged in 2020-08, with the labels that each got.

#1502 [releng] Bootstrap against 2.23.0.M2
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1501 removed obsolete org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.builder.tests/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.builder/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.common.types.eclipse.tests/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.common.types.ui/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.eclipse.tests/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.ui.codetemplates.ui/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.ui.codetemplates/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/.settings/org.eclipse.xtend.shared.ui.prefs
  org.eclipse.xtext.xtext.ui/.settings/org.eclipse.xtend.shared.ui.prefs
Labels: releng

#1506 always archive ui test logs
  Jenkinsfile
Labels: releng

#1514 run tests with java 11 (provisional fix)
  Jenkinsfile
Labels: releng

#1520 [releng] Bootstrap against 2.23.0.M3
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng

#1521 [eclipse/xtext-core#1561] Remove model listener when the railroad view is closed
  org.eclipse.xtext.xtext.ui.graph/src/org/eclipse/xtext/xtext/ui/graph/RailroadSynchronizer.java
Labels: performance

#1526 [releng] Bootstrap against 2.23.0
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng
