Repository eclipse/xtext-eclipse, pull requests merged in 2021-05, with the labels that each got.

#1672 revert use of staging in domain model
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
Labels: releng

#1674 bump exec-maven-plugin to 3.0.0
  org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
Labels: releng

#1671 Make sure the auto build is triggered after a force kill
  org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/BuilderStateDiscarder.java
Labels: bug

#1675 update to maven 3.8.1
  Jenkinsfile
Labels: releng

#1677 [releng] Bootstrap against 2.26.0.M1
  releng/org.eclipse.xtext.tycho.parent/pom.xml
Labels: bot, releng
